---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backupbuckets.extensions.gardener.cloud
spec:
  group: extensions.gardener.cloud
  versions:
  - name: v1alpha1
    served: true
    storage: true
  version: v1alpha1
  scope: Cluster
  names:
    plural: backupbuckets
    singular: backupbucket
    kind: BackupBucket
    shortNames:
    - bb
  additionalPrinterColumns:
  - name: Type
    type: string
    description: The type of the cloud provider for this resource.
    JSONPath: .spec.type
  - name: Region
    type: string
    description: The region into which the backup bucket should be created.
    JSONPath: .spec.region
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  subresources:
    status: {}
