---
apiVersion: v1
kind: Secret
metadata:
  name: cloudprovider
  namespace: shoot--foo--bar
type: Opaque
data:
# accessKeyID: base64(access-key-id)
# secretAccessKey: base64(secret-access-key)
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: BackupEntry
metadata:
  name: shoot--foo--bar--sd34f
  namespace: backup-garden
spec:
  type: aws
  region: eu-west-1
  bucket: seed--aws--fg2d6
  secretRef:
    name: cloudprovider
    namespace: shoot--foo--bar